server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8000
  servlet:
    register-default-servlet: on

spring:
  datasource:
    password: code
    url: jdbc:postgresql://localhost:5432/template
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
jwt:
  secret: mak*(!NSKJ@(*21
  expiresIn: 86400000

